### PR TITLE
Updated index.html for proper HTML/HTML5 layout.

### PR DESCRIPTION
**Pull request by ghost**
Put the content and content-dependent script links within the document body

### CODE REVIEW

**Comment by DeleteThisAcount** [comment]
So what does this do?

**Comment by ghost** [comment]
Keeps to standards and helps search engines that use modern page identification to know that the div is actual page content and not just arbitrary HTML. It also helps someone who's new to the code to know what's what. Mainly it's organisation. It doesn't affect the way the page looks but is a good practice. The very basics of HTML state that every HTML document should have a body, head and html tag at least. You were missing the body tag.

**Comment by DeleteThisAcount** [comment]
Will it change the way it works?

**Comment by ghost** [comment]
No. It doesn't change anything the user will see, it's just a better practice when coding in HTML.

**Pull request merged**
