### PR TITLE
Cleared div on first focus

### PR DESCRIPTION
**Pull request by andybrwr**
basically what herohamp tried

### CODE REVIEW

**Comment by DeleteThisAcount** [comment]
So what does this do?

**Comment by andybrwr** [comment]
On the first click on the div, the words "Type here!" are removed

**Comment by DeleteThisAcount** [comment]
oh ok then

**Comment by DeleteThisAcount** [comment]
yyay works

**Comment by andybrwr** [comment]
yay

**Comment by DeleteThisAcount** [comment]
YAY

**Pull request merged**
